#pragma once

#define DISTRHO_PLUGIN_BRAND "BALEZ"
#define DISTRHO_PLUGIN_NAME "BALEZverb"
#define DISTRHO_PLUGIN_URI "https://mxs.sbrk.org/"

#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_PROGRAMS 1
#define DISTRHO_UI_USER_RESIZABLE 1
